/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HeapNative */

#ifndef _Included_HeapNative
#define _Included_HeapNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HeapNative
 * Method:    heapNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HeapNative_heapNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
